export const GET_PLAYERS_RESPONSE = 'GET_PLAYERS_RESPONSE';
export const GET_PLAYER_RESPONSE = 'GET_PLAYER_RESPONSE';
export const ADD_NEW_PLAYER_RESPONSE = 'ADD_NEW_PLAYER_RESPONSE';
export const UPDATE_EXISTING_PLAYER_RESPONSE = 'UPDATE_EXISTING_PLAYER_RESPONSE';
export const DELETE_PLAYER_RESPONSE = 'DELETE_PLAYER_RESPONSE';

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';
